###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)  
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


  
spring:
  application:
    name:  app-elvis-goods
  redis:
    host: 192.168.43.29
    port: 6379
    password: zk201314

###数据库相关连接      
  datasource:
    username: root
    password: zk201314
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elvis_goods?useUnicode=true&characterEncoding=UTF-8
  data:
    elasticsearch:
    ####集群名称
     cluster-name: elasticsearch-cluster
    ####地址 
     cluster-nodes: 192.168.43.29:9300
  kafka:
    # kafka服务器地址(可以多个)
    bootstrap-servers: 192.168.43.29:9092
