spring:
  application:
    name: app-elvis-xxl-sso-server
  freemarker:
    settings:
      number_format: 0.##########
    charset: UTF-8
    request-context-attribute: request
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka   
server:
  port: 8080
  servlet:
    context-path: /xxl-sso-server

xxl:
  sso:
    redis:
      address: redis://xxl-sso:zk201314@192.168.43.29:6379
      password: zk201314
      expire:
        minite: 1440