###服务启动端口号
server:
  port: 8600
###服务名称(服务注册到eureka名称)  
#spring:
#    application:
#        name: app-mayikt-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka


  
spring:
  application:
    name:  app-elvis-pay
  redis:
    host: 192.168.43.29
    port: 6379
    password: zk201314
###数据库相关连接      
  datasource:
    username: root
    password: zk201314
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elvis_pay?useUnicode=true&characterEncoding=UTF-8
  rabbitmq:
    ####连接地址
    host: 127.0.0.1
    ####端口号
    port: 5672
    ####账号
    username: guest
    ####密码
    password: guest
    ### 地址
    virtual-host: /admin_host
    ###开启消息确认机制 confirms
    publisher-confirms: true
    publisher-returns: true
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.elvis.member.mapper: DEBUG

###多线程配置
threadPool:
  ###核心线程数
  corePoolSize: 10
  ###最大线程数
  maxPoolSize: 20
  ##  队列容量
  queueCapacity: 16